---
title: "GWAS_data_organization_for_plotgardener"
author: "Sara Lago"
date: "2025-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load required libraries:
```{r libraries}
library(dplyr)

```


```{r read GWAS}
# Read the complete table
man.data <- read.table("C:/Users/sarlago/Documents/R scripts/Shiny/ShinyTest/data/GWAScatalog_KidneyDisease/26831199-GCST003374-EFO_0003884.h.tsv.gz", sep = "\t", header = T) 

# remove NAs
man.data <-  man.data[!is.na(man.data$hm_chrom),]
# paste chr to chr name
man.data$hm_chrom <- paste("chr", man.data$hm_chrom, sep="")
# select just the columns with the required info and write output to file
man.data %>% 
  select("hm_chrom", "hm_pos", "p_value", "hm_rsid") %>% 
  write.table("C:/Users/sarlago/Documents/R scripts/Shiny/ShinyTest/data/GWAScatalog_KidneyDisease/26831199-GCST003374-EFO_0003884.h.selectedCol.tsv.gz", sep="\t", col.names = c("chrom", "pos", "p", "snp"), row.names = F, quote = F)

unique(man.data$hm_chrom)
```




```{r sesionInfo, echo=FALSE}
sessionInfo()
```

