---

default:

    # Set here the parameters related to the input files path and extensions
  # Data directory
  data.dir: "C:/Users/sarlago/Documents/Public Datasets/Kidney human tissues/"
  # bigWig directory and files final pattern or complete name (can correspond to one or more tracks), ordered file name to visualize. If empty type " " or [""] in names. OK
  bw.dir: "GSE166547_peaks_and_bigwigs/RAw"
  bw.ext: "Cluster.*[0-9].bw"
  bw.names: ["1_PT1", "10_CD_ICA1", "11_PT5", "12_CD_PC2", "13_PT6", "14_CD_ICA2", "15_MES", "16_LOH", "18_DCT2", "19_LEUK", "2_PODO", "20_PT7", "3_DCT1", "4_PT2", "5_PT3", "6_CD_PC1", "7_ENDO", "8_PT4", "9_1_PTPL", "9_2_PEP"]
  # bedpe directory and files final pattern, ordered file name to visualize. If empty type "  " or [""] in names. OK
  bedpe.dir: "  " #"Kidney multiome"
  bedpe.ext: "  " #"Open4Gene.GWAS.ID.tableS21.hg38.bedpe"
  bedpe.names: [] #["Open4Gene links"]
  # bed directory and files final pattern, ordered file name to visualize. If empty type "  " or [""] in names.
  bed.dir: "Kidney multiome"
  bed.ext: "TFrPeakCluster_hg38.bed.gz|snATAC.resolved.ATAC.Peaks.500bp_h38.bed"
  bed.names: ["ATAC peak", "TFBS"]
  # hic directory and files final pattern, ordered file name to visualize. If empty type "  " or [""] in names. Use "  " in presence of subfolders with space in name
  hic.dir: "  "
  hic.ext: "  "
  hic.names: [""]
  # GWAS directory and files final pattern, ordered file name to visualize. If empty type "  " or [""] in names.
  gwas.dir: "Kidney multiome/Figshare26299093"
  gwas.ext: "relocatedCol.hg38.tsv.gz"
  gwas.names: ["eGFRcrea GWAS"]
  # categorical bed file.If empty type "  " or [""] in names.
  cat.dir: "Kidney multiome"
  cat.file: "ChromHMM_hg38_categorical.bed"
  cat.names: ["Chromatin State"]
  # file with chromosomes and centromeres coordinates
  chrom.cen: "C:/Users/sarlago/Documents/Genome annotation files/hg38/chrom_centromeres_hg38.txt"
  # file with desired genome genes hgnc symbol and coordinates
  genes.hgnc: "C:/Users/sarlago/Documents/Genome annotation files/hg38/hg38_hgnc_symbol_cleaned.bed"