---
title: "get_hgnc_symbol_hg38"
author: "Sara Lago"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##------- This below is the version that works better

### retrieve list of all genes hg38 default and save them in a vector (g)
```{r}
library(org.Mm.eg.db)
x <- org.Mm.egSYMBOL
mapped_genes <- mappedkeys(x)
xx <- as.list(x[mapped_genes])
g <- unique(unlist(unname(xx[1:length(xx)])))
```

### Exploit biomart to retrieve the coordinates and the gene symbol together
```{r}
library(biomaRt)
library(dplyr)

ensembl <-useEnsembl(biomart = 'genes', 
                       dataset = 'mmusculus_gene_ensembl',
                       version = 102) # this is hte version for GRCm38 - mm10
ensembl <- useDataset("mmusculus_gene_ensembl",mart=ensembl)
getBM <- getBM(attributes=c('chromosome_name', 'start_position', 'end_position', 'strand', 'mgi_symbol'),
      values=list(g),
      mart=ensembl)
getBM <- getBM[!getBM$mgi_symbol =="",]
  # filter out the PATCH chromosomes by just keeping the standard ones:
  getBM <- dplyr::filter(getBM, chromosome_name %in% c(1:19, "X", "Y"))
  # check chr filtering:
  unique(getBM$chromosome_name)
  # For genes that are duplicated keep just the largest coordinates:
    # find duplicates
  duplicates <- unique(getBM[duplicated(getBM$mgi_symbol), 5])
    # save new start and end coordinates and chr name
  chr.new <- c()
  start.new <- c()
  end.new <- c()
  strand.new <- c()
  mgi.new <- c()
  for (d in duplicates){
   d.BM <- dplyr::filter(getBM, mgi_symbol == d)
    print(paste(d, ":", d.BM$chromosome_name))
   # some times the same gene is reported on two chromosomes, especially when considering X and Y chromosomes. 
   # In such cases we need to keep the duplicated gene name and the respective coordinates
   # Similarely the same gene can be encoded on different strands either on the same chromnosome or on different chromosomes, therefore we need to consider all of the options
    # 1. group by chromosome:
   d.BM.chr <- group_split(d.BM, chromosome_name)
   for (c in 1:length(d.BM.chr)){
     d.BM.strand <- group_split(d.BM.chr[[c]], strand)
     for (s in 1:length(d.BM.strand)){
         chr.new <- c(chr.new, unique(d.BM.strand[[s]]$chromosome_name))
         start.new <- c(start.new, min(d.BM.strand[[s]]$start_position))
         end.new <- c(end.new, max(d.BM.strand[[s]]$end_position))
         strand.new <- c(strand.new, unique(d.BM.strand[[s]]$strand))
         mgi.new <- c(mgi.new, d)
       } 
     }
   }
   
  
    
  # merge new info into a data.frame
  new.BM <- data.frame(chromosome_name = chr.new,
                       start_position = start.new,
                       end_position = end.new,
                       strand = strand.new,
                       mgi_symbol = mgi.new)
  # remove duplicates form the initial data.frame
  getBM <- getBM[!getBM$mgi_symbol %in% duplicates,]
  getBM <- rbind(getBM, new.BM)

```


### Export the cleaned annotation table:
```{r}
  write.table(getBM, "GRCm38_symbol_cleaned.bed", col.names = T, row.names = F, quote = F, sep = "\t")
```

## SessionInfo
```{r sessionINfo}
sessionInfo()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
