---
title: "get_hgnc_symbol_hg38"
author: "Sara Lago"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##------- This below is the version that works better
### retrieve list of all genes hg38 default and save them in a vector (g)

```{r}
library(org.Hs.eg.db)
x <- org.Hs.egSYMBOL
mapped_genes <- mappedkeys(x)
xx <- as.list(x[mapped_genes])
g <- unique(unlist(unname(xx[1:length(xx)])))
```

### Exploit biomart to retrieve the coordinates and the gene symbol together
```{r}
library(biomaRt)
ensembl <- useMart("ensembl")
ensembl <- useDataset("hsapiens_gene_ensembl",mart=ensembl)
getBM <- getBM(attributes=c('chromosome_name', 'start_position', 'end_position', 'strand', 'hgnc_symbol'),
      filters=c('hgnc_symbol'),
      values=list(g),
      mart=ensembl)
  # filter out the PATCH chromosomes by just keeping the standard ones:
  getBM <- dplyr::filter(getBM, chromosome_name %in% c(1:22, "X", "Y"))
  # check chr filtering:
  unique(getBM$chromosome_name)
  # For genes that are duplicated keep just the largest coordinates:
    # find duplicates
  duplicates <- unique(getBM[duplicated(getBM$hgnc_symbol), 5])
    # save new start and end coordinates and chr name
  chr.new <- c()
  start.new <- c()
  end.new <- c()
  strand.new <- c()
  hgnc.new <- c()
  for (d in duplicates){
   d.BM <- dplyr::filter(getBM, hgnc_symbol == d)
    print(paste(d, ":", d.BM$chromosome_name))
   # some times the same gene is reported on two chromosomes, especially when considering X and Y chromosomes. 
   # In such cases we need to keep the duplicated gene name and the respective coordinates
   chrs <- unique(d.BM$chromosome_name)
   if (length(chrs) > 1){
     chr.new <- c(chr.new, d.BM$chromosome_name)
     start.new <- c(start.new, d.BM$start_position)
     end.new <- c(end.new, d.BM$end_position)
     strand.new <- c(strand.new, d.BM$strand)
     hgnc.new <- c(hgnc.new, rep(d, length(d.BM$chromosome_name)))
   } else {
   chr.new <- c(chr.new, chrs)
   start.new <- c(start.new, min(d.BM$start_position))
   end.new <- c(end.new, max(d.BM$end_position))
   strand.new <- c(strand.new, unique(d.BM$strand))
   hgnc.new <- c(hgnc.new, d)
   }
  }
  # merge new info into a data.frame
  new.BM <- data.frame(chromosome_name = chr.new,
                       start_position = start.new,
                       end_position = end.new,
                       strand = strand.new,
                       hgnc_symbol = hgnc.new)
  # remove duplicates form the initial data.frame
  getBM <- getBM[!getBM$hgnc_symbol %in% duplicates,]
  getBM <- rbind(getBM, new.BM)

# rename columns to uniform calling
colnames(getBM) <-  c('chromosome_name', 'start_position', 'end_position', 'strand', 'gene_symbol')  

```


### Export the cleaned annotation table:
```{r}
  write.table(getBM, "hg38_gene_symbol_cleaned.bed", col.names = T, row.names = F, quote = F, sep = "\t")
```

## SessionInfo
```{r sessionINfo}
sessionInfo()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
