## Environment variable GV_TESTFILES points to directory with our test files.
TFDIR <- Sys.getenv("GV_TESTFILES")
## Minimal requirements: a) environment variable is set and points to directory.
stopifnot("Please set enviroment variable `GV_TESTFILES` to test file directory." = TFDIR!="")
stopifnot("Directory referenced by `GV_TESTFILES` does not exist" = dir.exists(TFDIR))

library(testthat)

## These are used in the validation functions via namespace referencing (::).
## We explicitly require them here in order to have not errors being thrown,
## which are then causing confusion in the unit test suite.

library(rtracklayer)
library(strawr)

# Only requires `testthat` library! Just run:
#
# GV_TESTFILES=/path/to/tests Rscript utest/test-file_validation_function.R
#
# from the Docker_file directory or, if in Rstudio, given the working directory
# is also Docker_file and that `GV_TESTFILES` is set appropriately.
#
# test_file("utest/test-file_validation_function.R")

source(file.path(BASEDIR, "file_validation_function.r"))

E_EXT_BED <- "Expected extension: bed, txt, tsv"
E_EXT_BW <- "Expected extension: bw, bigwig"
E_EXT_HIC <- "Expected extension: hic"
E_GWAS_MISS_COL <- "Missing required columns: chrom, pos, p, snp"
E_MISS_CATBED_COL <- "Missing required columns: chr, start, end, category"

IMPOSSIBLEFFN <- file.path("/", "a87jb3b", "jshbs", "does-not-exist-i-hope.")

test_that("BED", {
  dirnm <- file.path(TFDIR, "bed_bam")
  res <- validateBed(paste0(IMPOSSIBLEFFN, "bed"))
  expect_false(res$valid)
  res <- validateBed(file.path(dirnm, "bed_valid.bed"))
  expect_true(res$valid)
  res <- validateBed(file.path(dirnm, "bed_invalid1.bed"))
  expect_false(res$valid)
  expect_match(res$errors, E_BED_MIN3COL)
  res <- validateBed(file.path(dirnm, "bed_invalid2.bed"))
  expect_false(res$valid)
  expect_match(res$errors, E_CHROM_CHR)
  res <- validateBed(file.path(dirnm, "bed_invalid3.csv"))
  expect_false(res$valid)
  expect_match(res$errors, E_EXT_BED)
  res <- validateBed(file.path(dirnm, "bed_invalid4.bed"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_BED_NO_HDR)
  expect_match(res$errors, all = FALSE, E_COL2_NUM)
  expect_match(res$errors, all = FALSE, E_COL3_NUM)
  expect_match(res$errors, all = FALSE, E_START_END)
  res <- validateBed(file.path(dirnm, "bed_invalid5.bed"))
  expect_false(res$valid)
  expect_match(res$errors, E_START_END)
})

test_that("BigWig", {
  dirnm <- file.path(TFDIR, "bigwig")
  res <- validateBed(paste0(IMPOSSIBLEFFN, "bw"))
  expect_false(res$valid)
  res <- validateBigWig(file.path(dirnm, "bigwig_valid.bw"))
  expect_true(res$valid)
  res <- validateBigWig(file.path(dirnm, "bigwig_invalid1_randomtext.txt"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_EXT_BW)
  if( .Platform$OS.type != "windows" )
    expect_match(res$errors, all = FALSE, E_VALID_BW)
  if( .Platform$OS.type != "windows" ) {
    res <- validateBigWig(file.path(dirnm, "bigwig_invalid2_emptyfile.bw"))
    expect_false(res$valid)
    expect_match(res$errors, E_VALID_BW)
  }
  res <- validateBigWig(file.path(dirnm, "bigwig_invalid3_wrongextension.csv"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_EXT_BW)
  if( .Platform$OS.type != "windows" )
    expect_match(res$errors, all = FALSE, E_VALID_BW)
  res <- validateBigWig(file.path(dirnm, "bigwig_invalid4_randombinary.bw"))
  ## Unfortunately, according to import's help page, no support for Win$ here.
  if( .Platform$OS.type != "windows" ) {
    expect_false(res$valid)
    expect_match(res$errors, E_VALID_BW)
  }
})

test_that("BEDPE", {
  dirnm <- file.path(TFDIR, "bedpe")
  res <- validateBedpe(paste0(IMPOSSIBLEFFN, "bedpe"))
  expect_false(res$valid)
  res <- validateBedpe(file.path(dirnm, "bedpe_valid.bedpe"))
  expect_true(res$valid)
  res <- validateBedpe(file.path(dirnm, "bedpe_valid_header.bedpe"))
  expect_true(res$valid)
  res <- validateBedpe(file.path(dirnm, "bedpe_invalid1.bedpe"))
  expect_false(res$valid)
  expect_match(res$errors, E_BEDPE_6COL)
  res <- validateBedpe(file.path(dirnm, "bedpe_invalid2.bedpe"))
  expect_false(res$valid)
  expect_match(res$errors, E_FOPEN)
  res <- validateBedpe(file.path(dirnm, "bedpe_invalid3.bedpe"))
  expect_false(res$valid)
  expect_match(res$errors, E_BEDPE_6COL)
  res <- validateBedpe(file.path(dirnm, "bedpe_invalid4.bedpe"))
  expect_false(res$valid)
  expect_match(res$errors, E_COL1_CHROM)
  res <- validateBedpe(file.path(dirnm, "bedpe_invalid5.bedpe"))
  expect_false(res$valid)
  expect_match(res$errors, E_COL2_NUM)
  res <- validateBedpe(file.path(dirnm, "bedpe_invalid6.bedpe"))
  expect_false(res$valid)
  expect_match(res$errors, E_BEDPE_1_START_END)
  res <- validateBedpe(file.path(dirnm, "bedpe_invalid7.bedpe"))
  expect_false(res$valid)
  expect_match(res$errors, E_BEDPE_2_START_END)
  res <- validateBedpe(file.path(dirnm, "bedpe_invalid8.bedpe"))
  expect_false(res$valid)
  expect_match(res$errors, E_BEDPE_ORDER)
})

test_that("HiC", {
  dirnm <- file.path(TFDIR, "hic")
  res <- validateHic(paste0(IMPOSSIBLEFFN, "hic"))
  expect_false(res$valid)
  res <- validateHic(file.path(dirnm, "hic_valid.hic"))
  expect_true(res$valid)
  res <- validateHic(file.path(dirnm, "hic_invalid1_wrongext.sh"))
  expect_false(res$valid)
  expect_match(res$errors, E_EXT_HIC)
  res <- validateHic(file.path(dirnm, "hic_invalid2_emptyfile.hic"))
  expect_false(res$valid)
  expect_match(res$errors, E_VALID_HIC)
  res <- validateHic(file.path(dirnm, "hic_invalid3_nothic.hic"))
  expect_false(res$valid)
  expect_match(res$errors, E_VALID_HIC)
  res <- validateHic(file.path(dirnm, "hic_invalid4_randombinary.hic"))
  expect_false(res$valid)
  expect_match(res$errors, E_VALID_HIC)
  res <- validateHic(file.path(dirnm, "hic_invalid4_randombinary.hic"))
  expect_false(res$valid)
  expect_match(res$errors, E_VALID_HIC)
})

test_that("GWAS", {
  dirnm <- file.path(TFDIR, "gwas")
  res <- validateGWAS(paste0(IMPOSSIBLEFFN, "tsv"))
  expect_false(res$valid)
  res <- validateGWAS(file.path(dirnm, "gwas_valid.tsv"))
  expect_true(res$valid)
  res <- validateGWAS(file.path(dirnm, "gwas_invalid1_noheader.tsv"))
  expect_false(res$valid)
  expect_match(res$errors, E_GWAS_MISS_COL)
  res <- validateGWAS(file.path(dirnm, "gwas_invalid2_wrongext.docx"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, "Expected extension: tsv, txt, gz")
  expect_match(res$errors, all = FALSE, E_GWAS_MISS_COL)
  res <- validateGWAS(file.path(dirnm, "gwas_invalid3_wrongheader.tsv"))
  expect_false(res$valid)
  expect_match(res$errors, E_GWAS_MISS_COL)
  res <- validateGWAS(file.path(dirnm, "gwas_invalid4_emptyfile.tsv"))
  expect_false(res$valid)
  expect_match(res$errors, E_GWAS_MISS_COL)
  res <- validateGWAS(file.path(dirnm, "gwas_invalid5_randomtext.txt"))
  expect_false(res$valid)
  expect_match(res$errors, E_GWAS_MISS_COL)
  res <- validateGWAS(file.path(dirnm, "gwas_invalid6_wrongchr.tsv"))
  expect_false(res$valid)
  expect_match(res$errors, E_CHROM_CHR)
  res <- validateGWAS(file.path(dirnm, "gwas_wrong7_posnotnum.tsv"))
  expect_false(res$valid)
  expect_match(res$errors, E_POS_NUM)
  res <- validateGWAS(file.path(dirnm, "gwas_invalid8_pnonum.tsv"))
  expect_false(res$valid)
  expect_match(res$errors, E_P_NUM)
})

test_that("Categorical BED", {
  dirnm <- file.path(TFDIR, "cat_bed")
  res <- validateCategoricalBed(paste0(IMPOSSIBLEFFN, "bed"))
  expect_false(res$valid)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_valid.bed"))
  expect_true(res$valid)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid1_wrongext.png"))
  expect_false(res$valid)
  expect_match(res$errors, E_EXT_BED)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid2_randomtext.txt"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_MISS_CATBED_COL)
  expect_match(res$errors, all = FALSE, E_START_NUM)
  expect_match(res$errors, all = FALSE, E_END_NUM)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid3_emptyfile.bed"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_MISS_CATBED_COL)
  expect_match(res$errors, all = FALSE, E_START_NUM)
  expect_match(res$errors, all = FALSE, E_END_NUM)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid4_randombinary.bed"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_MISS_CATBED_COL)
  expect_match(res$errors, all = FALSE, E_START_NUM)
  expect_match(res$errors, all = FALSE, E_END_NUM)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid5_nocat.bed"))
  expect_false(res$valid)
  expect_match(res$errors, "Missing required columns: category")
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid6_noheader.bed"))
  expect_match(res$errors, all = FALSE, E_MISS_CATBED_COL)
  expect_match(res$errors, all = FALSE, E_START_NUM)
  expect_match(res$errors, all = FALSE, E_END_NUM)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid7_wrongchr.bed"))
  expect_false(res$valid)
  expect_match(res$errors, E_CHROM_CHR)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid8_coordnotnum.bed"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_START_NUM)
  expect_match(res$errors, all = FALSE, E_START_END)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid9_coordwrongorder.bed"))
  expect_false(res$valid)
  expect_match(res$errors, E_START_END)
  res <- validateCategoricalBed(file.path(dirnm, "catbed_invalid10_catempty.bed"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_START_NUM)
  expect_match(res$errors, all = FALSE, E_END_NUM)
})

test_that("Region file", {
  dirnm <- file.path(TFDIR, "region_table")
  res <- validateRegionFile(paste0(IMPOSSIBLEFFN, "bed"))
  expect_false(res$valid)
  res <- validateRegionFile(file.path(dirnm, "reg_valid.bed"))
  expect_true(res$valid)
  res <- validateRegionFile(file.path(dirnm, "reg_valid2.bed"))
  expect_true(res$valid)
  res <- validateRegionFile(file.path(dirnm, "reg_invalid1_wrognext.jpg"))
  expect_false(res$valid)
  expect_match(res$errors, E_EXT_BED)
  res <- validateRegionFile(file.path(dirnm, "reg_invalid2_nocoord.tsv"))
  expect_false(res$valid)
  expect_match(res$errors, E_REG_MIN3COL)
  res <- validateRegionFile(file.path(dirnm, "reg_invalid3_wrongchr.bed"))
  expect_false(res$valid)
  expect_match(res$errors, E_CHROM_CHR)
  res <- validateRegionFile(file.path(dirnm, "reg_invalid4_wrongcoord.bed"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_COL2_NUM)
  expect_match(res$errors, all = FALSE, E_COL3_NUM)
  res <- validateRegionFile(file.path(dirnm, "reg_invalid5_revcoord.bed"))
  expect_false(res$valid)
  expect_match(res$errors, E_START_END)
  res <- validateRegionFile(file.path(dirnm, "reg_invalid6_empty.txt"))
  expect_false(res$valid)
  expect_match(res$errors, E_REG_MIN3COL)
  res <- validateRegionFile(file.path(dirnm, "reg_invalid7_randomtext.tsv"))
  expect_false(res$valid)
  expect_match(res$errors, E_REG_MIN3COL)
  res <- validateRegionFile(file.path(dirnm, "reg_invalid8_header.bed"))
  expect_false(res$valid)
  expect_match(res$errors, all = FALSE, E_COL2_NUM)
  expect_match(res$errors, all = FALSE, E_COL3_NUM)
})
